### ISSUE TITLE
"module 'redis.connection' has no attribute 'parse_url'" when adding a server

### ISSUE THREAD

**Issue by philgyford** [ionelmc/django-redisboard#48]
I've installed django-redisboard and am trying to add a Redis server in the Django admin.

When I enter this as the URL: `redis://@localhost:6379/0` and submit the form, the error message shown for that field is:

>"module 'redis.connection' has no attribute 'parse_url'"

![Screenshot 2022-09-10 at 18 01 37](https://user-images.githubusercontent.com/66670/189493948-efe3bdde-313c-47ee-afd4-f4b3d7c49920.png)

This is currently a local dev set-up using Docker. I'm using Django 4.1.1, django-redis 5.2.0, django-redisboard 8.3.0, and redis 3.5.3.

**Comment by philgyford** [comment]
I'm guessing that this is because I'm using redis 3.5.3 and `parse_url` only exists in later versions? It looks like I have 3.5.3 because I'm using [django-q](https://github.com/Koed00/django-q/) which pip-tools thinks requires redis < 4.0.0, although I can't see where that's defined in django-q's setup.

```
  redis<4.0.0,>=3.5.3 (from django-q==1.3.9->-r requirements.in (line 7))
  redis>=3.5 (from django-redisboard==8.3.0->-r requirements.in (line 9))
  redis!=4.0.0,!=4.0.1,>=3 (from django-redis==5.2.0->-r requirements.in (line 8))
```

But django-redisboard says it should work with redis >= 3.5, which maybe isn't actually the case any more?

**Comment by ionelmc** [comment]
Turns out the minimum supported version for redisboard is redis 4.1 (we use select api introduced in 4.1 too). I mean we could have support for older redis client but on the other hand I django-q shouldn't have this in the it's deps...
```
redis = { version = "^3.5.3", optional = true }
```

Imo the correct place to report this problem is django-q's bugtracker.

I'll fix redisboard min requirements tho (the proper way, not how django-q does it).

**Comment by ionelmc** [comment]
Note that you can install redisboard standalone - seems like the right thing to do since you're using a localhost connection (you'll have a redisboard bin that starts an admin for you).

If you really want support for 2 year old redis client you can also make a PR but it seems wasteful to me :-)

**Comment by philgyford** [comment]
Many thanks - updating the min requirements is fine by me, thank you!

Out of interest, because I don't know much about this side of things, why is django-q's method of specifying requirements wrong?

**Comment by ionelmc** [comment]
They just copied some random stuff from poetry's docs: https://python-poetry.org/docs/dependency-specification/

"^" operator is more of a application thing (you want the latest patch release in your application, but not the latest major release that's likely to break all sorts of thing)

That operator is not really good for libraries. Don't look at requests and think what they do is a good idea in general ("urllib3>=1.21.1,<1.27"):
1. nobody else really depends on urllib3
2. mostly the same ppl maintain those 2 libraries, thus they have a very good grip over release schedules

In general you want to let the users resolve and pin the right dependency versions, and *only* have an upper constraint when you're 100% sure it will break stuff.

**Comment by ionelmc** [comment]
Clarification: when you're 100% sure the new version would break stuff.

**Comment by philgyford** [comment]
Many thanks for the explanation, and for django-redisboard.
