### ISSUE TITLE
Error in `REDISBOARD_DETAIL_CONVERTERS` when `REDISBOARD_DETAIL_FILTERS` exists

### ISSUE THREAD

**Issue by jacklinke** [ionelmc/django-redisboard#47]
After upgrading from 7.0.1 to 8.0.0, I receive the following error:

```bash
  File "/usr/local/lib/python3.9/site-packages/redisboard/models.py", line 64, in <module>
2022-05-15T19:18:32.723274100Z     for name, converter in getattr(
2022-05-15T19:18:32.723282988Z AttributeError: 'list' object has no attribute 'items'
```

It looks like `REDISBOARD_DETAIL_CONVERTERS` grabs `REDISBOARD_DETAIL_FILTERS` from settings ([which is a list](https://github.com/ionelmc/django-redisboard#optional-django-settings)), but falls back to a default value which is a dictionary if the settings entry is not present. It then treats tries to split out the dictionary keys and values, but if `REDISBOARD_DETAIL_FILTERS` exists in the settings, we get a failure because it's a list and not a dictionary.

Rolling back to 7.0.1 resolves the issue for the time being.

**Comment by jacklinke** [comment]
BTW, big fan of this package! It's nice to not need to rely on flower or other tools outside of django to do some simple checks on my redis servers!

**Comment by ionelmc** [comment]
There we go, 8.0.1 released. There oughta be more tests to catch bugs like this one but well... so little time.
